competitions/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic.simple import direct_to_template

admin.autodiscover()

urlpatterns = patterns('',
    url('^$', direct_to_template, {'template': 'arena/home.html'}, name="arena.home"),
    url('^ajax/available/$', 'competitions.views.ajax_available', name="arena.ajax_available"),
    url('^ajax/owned/$', 'competitions.views.ajax_owned', name="arena.ajax_owned"),
    url('^ajax/bookmark/(\d+)/$', 'competitions.views.ajax_bookmark', name="arena.ajax_bookmark"),
    url('^ajax/remove/(\d+)/$', 'competitions.views.ajax_unbookmark', name="arena.ajax_unbookmark"),
    url('^ajax/compo/(\d+)/$', 'competitions.views.ajax_compo', name="arena.ajax_compo"),
    url('^ajax/vote/(\d+)/$', 'competitions.views.ajax_vote', name="arena.ajax_vote"),
    url('^ajax/unvote/(\d+)/$', 'competitions.views.ajax_unvote', name="arena.ajax_unvote"),
    url('^ajax/submit-entry/$', 'competitions.views.ajax_submit_entry', name="arena.ajax_submit_entry"),

    url('^create/$', 'competitions.views.create', name="arena.create"),
    url('^edit/(\d+)/$', 'competitions.views.edit', name="arena.edit"),
    url('^compete/(\d+)/$', 'competitions.views.competition', name="arena.compete"),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from django.views.generic.simple import direct_to_template, redirect_to

admin.autodiscover()

urlpatterns = patterns('',
    (r'^arena/', include('competitions.urls')),
    (r'^chat/', include('chat.urls')),
    (r'^workbench/', include('workshop.urls')),
    (r'^admin/', include(admin.site.urls)),

    url(r'^$', 'main.views.home', name='home'),

    url(r'^ajax/login_state/$', 'main.views.ajax_login_state', name="ajax_login_state"),
    # if you change this, change LOGIN_URL in settings too.
    url(r'^ajax/login/$', 'main.views.ajax_login', name="ajax_login"),
    url(r'^ajax/logout/$', 'main.views.ajax_logout', name="ajax_logout"),
    url(r'^ajax/comment/$', 'main.views.ajax_comment', name="ajax_comment"),
    url(r'^ajax/delete_comment/$', 'main.views.ajax_delete_comment', name="ajax_delete_comment"),
    url(r'^ajax/edit_comment/$', 'main.views.ajax_edit_comment', name="ajax_edit_comment"),

    url(r'^article/([\w\d-]+)/$', 'main.views.article', name='article'),

    url(r'^plans/$', 'main.views.plans', name='plans'),

    url(r'^user/(.+)/$', 'main.views.userpage', name='userpage'),
    url(r'^band/(.+)/$', 'main.views.bandpage', name='bandpage'),

    url(r'^login/$', 'main.views.user_login', name="user_login"),
    url(r'^logout/$', 'main.views.user_logout', name="user_logout"),
    url(r'^signup/$', 'main.views.user_register', name="register"),
    url(r'^signup/pending/$', 'main.views.register_pending', name="register_pending"),
    url(r'^signup/(.+)/$', 'main.views.user_register_plan', name="register_plan"),
    url(r'^confirm/(.+)/(.+)/$', 'main.views.confirm', name="confirm"),

    url(r'^contact/$', 'main.views.contact', name="contact"),
    
    url(r'^legal/$', direct_to_template, {'template': 'legal/home.html'}, name="legal"),
    url(r'^legal/privacy/$', direct_to_template, {'template': 'legal/policy.html'}, name="policy"),
    url(r'^legal/terms/$', direct_to_template, {'template': 'legal/terms.html'}, name="terms"),

    url(r'^account/$', 'main.views.account_plan', name="account"),
    url(r'^account/plan/$', 'main.views.account_plan', name="account.plan"),
    url(r'^account/email/$', 'main.views.account_email', name="account.email"),
    url(r'^account/preferences/$', 'main.views.account_preferences', name="account.preferences"),
    url(r'^account/password/$', 'main.views.account_password', name="account.password"),
    url(r'^account/password/reset/$', 'main.views.account_password_reset', name="account.password.reset"),

    url(r'^landing/$', 'main.views.landing', name='landing'),
    url(r'^dashboard/$', 'main.views.dashboard', name='dashboard'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^500/$', direct_to_template, {'template': '500.html'}, name='404'),
        url(r'^404/$', direct_to_template, {'template': '404.html'}, name='500'),
    )

competitions/models.py
from django.db import models
from django.contrib.auth.models import User
from base.models import SerializableModel

from datetime import datetime, timedelta

class Competition(SerializableModel):
    PUBLIC_ATTRS = (
        'title',
        'preview_theme',
        'preview_rules',
        'start_date',
        'submit_deadline',
        'have_listening_party',
        'listening_party_start_date',
        'listening_party_end_date',
        'vote_deadline',
        'vote_period_length',
        'chat_room',
        'host',
    )
    OWNER_ATTRS = (
        'theme',
        'rules',
    )

    title = models.CharField(max_length=256)

    # who created the competition
    host = models.ForeignKey(User)

    # optional
    theme = models.TextField(blank=True)
    # can entrants view the theme before it starts?
    preview_theme = models.BooleanField(default=False)

    # optional
    rules = models.TextField(blank=True)
    # can entrants view the rules before it starts?
    preview_rules = models.BooleanField(default=True)

    # when this competition was created
    date_created = models.DateTimeField()

    # when the theme is announced / when the competition starts
    start_date = models.DateTimeField()

    # deadline for submitting entries
    submit_deadline = models.DateTimeField()

    have_listening_party = models.BooleanField(default=False)
    # must be after submit_deadline, with enough time for
    # processing.
    listening_party_start_date = models.DateTimeField(blank=True, null=True)

    # set this date to listening_party_start_date. it will be updated when
    # someone submits an entry
    listening_party_end_date = models.DateTimeField(blank=True, null=True)

    # deadline for casting votes. must be after listening party end time,
    # which is undetermined. People must have at least 10 minutes to vote,
    # so when the processing from the submit_deadline is finished, it will
    # recalculate this value based on the then-known listening_party_end_date
    vote_deadline = models.DateTimeField(blank=True, null=True)

    # length of the voting period in seconds. Used to calculate vote_deadline
    # after listening party end date is computed.
    vote_period_length = models.BigIntegerField()

    # one chat room per competition
    chat_room = models.ForeignKey('chat.ChatRoom', blank=True, null=True)

    def themeVisible(self):
        return self.preview_theme or datetime.now() >= self.start_date

    def rulesVisible(self):
        return self.preview_rules or datetime.now() >= self.start_date

    def isClosed(self):
        "Returns True if and only if the competition is closed."
        now = datetime.now()
        return self.vote_deadline is not None and now >= self.vote_deadline

    def __unicode__(self):
        return "%s on %s" % (self.title, self.start_date)

    def save(self, *args, **kwargs):
        "Update populated fields before saving"
        if not self.id:
            self.date_created = datetime.now()
        self._save(*args, **kwargs)

    def _save(self, *args, **kwargs):
        "Save without any auto field population"
        super(Competition, self).save(*args, **kwargs)

    def to_dict(self, access=SerializableModel.PUBLIC, chains=[]):
        data = super(Competition, self).to_dict(access, chains)
        if self.themeVisible():
            data['theme'] = self.theme
        if self.rulesVisible():
            data['rules'] = self.rules
        return data

    def changeListeningPartyStartDate(self, date):
        """
        Use this method to change the lp start date. It automatically updates
        listening_party_end_date, vote_deadline, and have_listening_party
        Use date=None to mean no listening party.
        """
        vote_period_delta = timedelta(seconds=self.vote_period_length)
        if date is None:
            self.have_listening_party = False
            self.vote_deadline = self.submit_deadline + vote_period_delta
            self.listening_party_start_date = date
        else:
            self.have_listening_party = True
            lp_length = self.listening_party_end_date - self.listening_party_start_date
            self.vote_deadline = self.listening_party_end_date + vote_period_delta
            self.listening_party_start_date = date
            self.listening_party_end_date = date + lp_length

class ThumbsUp(SerializableModel):
    """
    A ThumbsUp is something a user gives to a competition entry.
    """
    PUBLIC_ATTRS = (
        'owner',
        'entry',
    )

    owner = models.ForeignKey(User)
    entry = models.ForeignKey('Entry')
    date_given = models.DateTimeField()

    def __unicode__(self):
        return "%s gives +1 to %s" % (self.owner, self.entry)

    def save(self, *args, **kwargs):
        "Update populated fields before saving"
        self.date_given = datetime.now()
        self._save(*args, **kwargs)

    def _save(self, *args, **kwargs):
        "Save without any auto field population"
        super(ThumbsUp, self).save(*args, **kwargs)

class Entry(SerializableModel):
    """
    An entrant submits an Entry to a Competition.
    """
    PUBLIC_ATTRS = (
        'competition',
        'owner',
        'song',
        'submit_date',
        'edit_date',
    )

    competition = models.ForeignKey(Competition)
    owner = models.ForeignKey(User)
    song = models.ForeignKey('main.Song')
    submit_date = models.DateTimeField()
    edit_date = models.DateTimeField()

    def __unicode__(self):
        return "%s in %s" % (self.song, self.competition)

    def save(self, *args, **kwargs):
        self.edit_date = datetime.now()
        if not self.id:
            self.submit_date = self.edit_date
        self._save(*args, **kwargs)

    def _save(self, *args, **kwargs):
        super(Entry, self).save(*args, **kwargs)

    def to_dict(self, access=SerializableModel.PUBLIC, chains=[]):
        data = super(Entry, self).to_dict(access, chains)
        if self.competition.isClosed():
            data['vote_count'] = ThumbsUp.objects.filter(entry=self).count()
        return data

competitions/forms.py
from competitions import design
from datetime import datetime, timedelta
from django import forms
from django.conf import settings

class TimeUnit:
    HOURS, DAYS, WEEKS = range(3)

    seconds_multiplier = {
        HOURS: 60*60,
        DAYS: 24*60*60,
        WEEKS: 7*24*60*60,
    }

class SubmitEntryForm(forms.Form):
    title = forms.CharField(max_length=100, error_messages={
        'required': design.this_field_is_required})
    comments = forms.CharField(max_length=1000, required=False, widget=forms.Textarea)
    file_mp3 = forms.FileField(error_messages={
        'required': design.this_field_is_required})
    file_source = forms.FileField(required=False)

    def clean_file_mp3(self):
        filename = self.cleaned_data['file_mp3']

        if filename[-3:].lower() != 'mp3':
            raise forms.ValidationError(design.uploaded_file_must_be_mp3)

        return filename

class CreateCompetitionForm(forms.Form):
    TIME_QUANTIFIERS = (
        (TimeUnit.HOURS, "hours"),
        (TimeUnit.DAYS, "days"),
        (TimeUnit.WEEKS, "weeks"),
    )

    title = forms.CharField(max_length=100, error_messages={'required': design.this_field_is_required})

    have_theme = forms.BooleanField(required=False)
    preview_theme = forms.BooleanField(required=False)
    theme = forms.CharField(max_length=20000, required=False, widget=forms.Textarea)

    have_rules = forms.BooleanField(required=False)
    preview_rules = forms.BooleanField(required=False)
    rules = forms.CharField(max_length=20000, required=False, widget=forms.Textarea)

    start_date = forms.DateTimeField(error_messages={'required': design.this_field_is_required})
    submission_deadline_date = forms.DateTimeField(error_messages={'required': design.this_field_is_required})

    have_listening_party = forms.BooleanField(required=False)
    party_immediately = forms.BooleanField(required=False)
    listening_party_date = forms.DateTimeField(required=False)

    vote_time_quantity = forms.IntegerField(max_value=12, min_value=1, initial=1, error_messages={'required': design.this_field_is_required})
    vote_time_measurement = forms.ChoiceField(choices=TIME_QUANTIFIERS, initial=TimeUnit.WEEKS, error_messages={'required': design.this_field_is_required})

    # add this many hours to the times to get the correct value
    tz_offset = forms.IntegerField(widget=forms.HiddenInput(), error_messages={'required': design.this_field_is_required})

    def _clean_start_date(self, in_start_date):
        if in_start_date <= datetime.now():
            msg = design.cannot_start_compo_in_the_past
            self._errors['start_date'] = self.error_class([msg])

    def clean(self):
        cleaned_data = self.cleaned_data

        in_lp_date = cleaned_data.get('listening_party_date')
        in_have_party = cleaned_data.get('have_listening_party')
        in_deadline = cleaned_data.get('submission_deadline_date')
        in_start_date = cleaned_data.get('start_date')
        in_tz_offset = cleaned_data.get('tz_offset')

        if in_tz_offset is None:
            msg = design.this_field_is_required
            self._errors['tz_offset'] = self.error_class([msg])
            return cleaned_data

        # adjust dates with tz_offset
        tz_delta = timedelta(hours=in_tz_offset)

        if in_lp_date is not None:
            in_lp_date += tz_delta
        if in_deadline is not None:
            in_deadline += tz_delta
        if in_start_date is not None:
            in_start_date += tz_delta

        if in_start_date is None:
            msg = design.this_field_is_required
            self._errors['start_date'] = self.error_class([msg])
            return cleaned_data

        self._clean_start_date(in_start_date)

        # clean submission_deadline_date
        min_deadline = in_start_date + timedelta(minutes=settings.MINIMUM_COMPO_LENGTH)
        if in_deadline < min_deadline:
            msg = design.give_at_least_x_minutes_to_work
            self._errors['submission_deadline_date'] = self.error_class([msg])

        # clean listening_party_date
        if not cleaned_data.get('party_immediately'):
            if in_have_party:
                if in_lp_date is None:
                    msg = design.if_you_want_lp_set_date
                    self._errors['listening_party_date'] = self.error_class([msg])
                elif in_lp_date < in_deadline:
                    msg = design.lp_gt_submission_deadline
                    self._errors['listening_party_date'] = self.error_class([msg])
        
        return cleaned_data

class EditCompetitionForm(CreateCompetitionForm):
    def _clean_start_date(self, in_start_date):
        pass

base/views.py
# Create your views here.

templates/arena/arena_base.html
{% extends 'base.html' %}

{% block title %}Arena - {{ block.super }}{% endblock %}

{% block css %}arena.css{% endblock %}

{% block extra_header %}
    <script type="text/javascript">
var server_time = new Date('{{ server_time }}');
var local_time = new Date();
    </script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jstparser-0.4.0.min.js"></script>
    {{ block.super }}
{% endblock %}

templates/arena/available.jst.html
<% (function (available) { %>
    <div id="public-competitions">
        <h2>Public Competitions</h2>
        <% var compo_list = available; %>
        <% var list_name = 'available'; %>
        <% if (compo_list.compos.length > 0) { %>
            {% include 'arena/compo_list.jst.html' %}
        <% } else { %>
            <p>Sorry, no competitions available right now.</p>
        <% } %>
    </div>
<% }(available)); %>

templates/arena/competition.html
{% extends 'arena/base.html' %}

{% block title %}{{ competition.title }} - {{ block.super }}{% endblock %}

{% block css %}competition.pre.css{% endblock %}

{% block extra_header %}
    {{ block.super }}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/webtoolkit.aim.js"></script>
    <script type="text/javascript">
        var competition_id = {{ competition.id }};
        var chatroom_id = {% if competition.chat_room %}{{ competition.chat_room.id }}{% else %}null{% endif %};
    </script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/login.pre.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/chat.pre.js"></script>
    {% include 'player/script_player.html' %}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/arena/competition.pre.js"></script>
{% endblock %}

{% block nav2 %}
    <div id="tools-wrapper">

    </div>
{% endblock %}

{% block content %}
    <div id="css-status">
        <h1>{{ competition.title }}</h1>
        <div id="status">
            {% include 'loading.html' %}
        </div>
        <div id="vote-status">
            {% include 'loading.html' %}
        </div>
    </div>
    <div id="info">
        {% include 'loading.html' %}
    </div>
    <div class="clear"></div>
    <div id="entry-chat-wrapper">
        <div id="entry-area">
            {% include 'loading.html' %}
        </div>
        <div id="chatroom-outer">
            {% include 'chat/chatroom.html' %}
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <div style="display: none;" id="submission">
        <h4>Your entry</h4>
        <div id="submit-entry">
            <form
                id="submission-form"
                method="post"
                enctype="multipart/form-data"
                action="{% url arena.ajax_submit_entry %}"
                onsubmit="return AIM.submit(this, {'onStart': SCCompo.submitEntryStartCallback, 'onComplete': SCCompo.submitEntryCompleteCallback})"
            >
            <fieldset>
            <input type="hidden" name="compo" value="{{ competition.id }}" />
                <table>
                    <tr>
                        <th><label for="entry-file-mp3">Your rendered song, in mp3 format:</label></th>
                        <td>
                            <input type="file" name="entry-file-mp3" id="entry-file-mp3" />
                        </td>
                    </tr>
                    <tr>
                        <th><label for="entry-file-source">(optional) Source project file:</label></th>
                        <td>
                            <input type="file" name="entry-file-source" id="entry-file-source" />
                            {% include "tips/entrySourceProjectFile.html" %}
                        </td>
                    </tr>
                    <tr>
                        <td>
                        </td>
                        <td>
                            <input type="checkbox" name="entry-open-source" id="entry-open-source" value="1" />
                            <label for="entry-open-source">Anyone can download my project file</label>
                            {% include 'tips/openSource.html' %}
                        </td>
                    </tr>
                    <tr>
                        <th><label for="entry-title">Song Title:</label></th>
                        <td><input type="text" id="entry-title" name="entry-title" value="" maxlength="100" /></td>
                    </tr>
                    <tr>
                        <th>
                            <label for="entry-comments">(optional) Author's Comments:</label>
                            <br/>(supports <a href="http://attacklab.net/showdown/">markdown</a>)
                        </th>
                        <td><textarea rows="10" cols="80" name="entry-comments" id="entry-comments"></textarea></td>
                    </tr>
                    <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="Submit" />
                        <input type="reset" value="Clear Form" />
                        <input id="cancel-submission" type="button" value="Cancel" />
                    </td>
                    </tr>
                </table>
            </fieldset>
            </form>
        </div>
    </div>
    <div id="current-entry">
        {% include 'loading.html' %}
    </div>
{% endblock %}

templates/arena/compo.jst.html
<div class="compo">
    <h4><%= compo.title %></h4>
    <% if (secondsUntil(compo.start_date) > 0) { %>
        <p>starts in <%= printableTimeUntil(compo.start_date) %></p>
    <% } else if (secondsUntil(compo.submit_deadline) > 0) { %>
        <p>submission deadline in <%= printableTimeUntil(compo.submit_deadline) %></p>
    <% } else if (compo.have_listening_party && secondsUntil(compo.listening_party_end_date) > 0) { %>
        <% if (localTime(compo.listening_party_start_date) > (new Date())) { %> 
            <p>listening party starting in
            <%= printableTimeUntil(compo.listening_party_start_date) %>
            </p>
        <% } else { %>
            <p>Listening party
            (<%= timeDisplaySince(compo.listening_party_start_date) %> / 
            <%= timeDisplayUntil(compo.listening_party_end_date) %>)</p>
        <% } %>
    <% } else if (secondsUntil(compo.vote_deadline) > 0) { %>
        <p>voting ends in <%= printableTimeUntil(compo.vote_deadline) %></p>
    <% } else { %>
        <p>ended on <%= formatDate(localTime(compo.submit_deadline)) %></p>
        <% if (compo.user_entered) { %>
            <p>you got <%= compo.vote_count %> votes</p>
        <% } %>
    <% } %>
    <div>
        <a href="/arena/compete/<%= compo.id %>/" id="compo-<%= compo.id %>-view">view</a>
        <% if (compo.bookmarked) { %>
            <a href="#" id="compo-<%= compo.id %>-remove">remove</a>
        <% } else { %>
            <a href="#" id="compo-<%= compo.id %>-bookmark">bookmark</a>
        <% } %>
    </div>
</div>

templates/arena/compo_info.jst.html
<% if (json.compo.have_theme || json.compo.have_rules) { %>
    <div id="infowrapper">
    <% if (json.compo.have_theme) { %>
        <div id="theme">
            <h3>Theme
            <span class="showhide">(<a href="#"><% if (theme_shown) { %>hide<% } else { %>show<% } %></a>)</span></h3>
            <div class="container"
                <% if (! theme_shown) { %> style="display: none;"<% } %>
            >
            <% if (json.compo.preview_theme) { %>
                <%+ Showdown.makeHtml(json.compo.theme) %>
            <% } else { %>
                <% if (Time.secondsUntil(json.compo.start_date) > 0) { %>
                    The theme will be announced as soon as the competition starts.
                <% } else { %>
                    <%+ Showdown.makeHtml(json.compo.theme) %>
                <% } %>
            <% } %>
            </div>
        </div>
    <% } %>
    <% if (json.compo.have_rules) { %>
        <div id="rules">
            <h3>Rules
            <span class="showhide">(<a href="#"><% if (rules_shown) { %>hide<% } else { %>show<% } %></a>)</span></h3>
            <div class="container"
                <% if (! rules_shown) { %> style="display: none;"<% } %>
            >
            <% if (json.compo.preview_rules) { %>
                <%+ Showdown.makeHtml(json.compo.rules) %>
            <% } else { %>
                <% if (Time.secondsUntil(json.compo.start_date) > 0) { %>
                    The rules will be announced as soon as the competition starts.
                <% } else { %>
                    <%+ Showdown.makeHtml(json.compo.rules) %>
                <% } %>
            <% } %>
            </div>
        </div>
    <% } %>
    <div class="clear"></div>
    </div>
<% } %>

templates/arena/compo_tools.jst.html
<% if (json.user.id === json.compo.host.id) { %>
    <ul id="tools">
        <li class="wrench">
            <a href="<%= urls.edit(json.compo.id) %>">Edit Competition</a>
        </li>
    </ul>
<% } else { %>
<% } %>

templates/arena/create.html
{% extends 'arena/base.html' %}

{% block title %}{% block create_title %}Create a Competition - {% endblock %}{{ block.super }}{% endblock %}

{% block css %}arena.pre.css{% endblock %}

{% block extra_header %}
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/anytimec.pre.css" />
    {{ block.super }}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/anytimec.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/arena/create.pre.js"></script>
{% endblock %}

{% block login %}
    {% include 'login_area.html' %}
{% endblock %}

{% block tools_wrapper %}{% endblock %}

{% block bread_crumb %}
    &gt;
    <span class="dest">Create Competition</span>
{% endblock %}

{% block content %}
    <div class="textblock">
        <h1>{% block h1_title %}Create a Public Competition{% endblock %}</h1>
        {% include 'form_errors.html' %}
        <form id="competition-form" method="post" action="." style="width: 500px;">
            <fieldset>
            {{ form.tz_offset }}
            <table>
                <tr>
                    <td colspan="2">
                        <h3>Title</h3>
                    </td>
                </tr>
                <tr>
                    <th><label for="id_title">Title:</label></th>
                    <td>{{ form.title.errors }}{{ form.title }}</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <h3>Theme</h3>
                    </td>
                </tr>
                <tr>
                    <th><label for="id_have_theme">Have theme:</label></th>
                    <td>{{ form.have_theme }}{% include 'tips/theme.html' %}</td>
                </tr>
                <tr id="div_theme">
                    <th><label for="id_theme">Theme:</label><br/>(supports <a href="http://attacklab.net/showdown/">markdown</a>)</th>
                    <td>{{ form.theme.errors }}{{ form.theme }}</td>
                </tr>
                <tr id="div_preview_theme">
                    <th><label for="id_preview_theme">Preview theme:</label></th>
                    <td>{{ form.preview_theme.errors }}{{ form.preview_theme }}{% include 'tips/previewTheme.html' %}</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <h3>Rules</h3>
                    </td>
                </tr>
                <tr>
                    <th><label for="id_have_rules">Have rules:</label></th>
                    <td>{{ form.have_rules.errors }}{{ form.have_rules }}</td>
                </tr>
                <tr id="div_rules">
                    <th><label for="id_rules">Rules:</label><br/>(supports <a href="http://attacklab.net/showdown/">markdown</a>)</th>
                    <td>{{ form.rules.errors }}{{ form.rules }}</td>
                </tr>
                <tr id="div_preview_rules">
                    <th><label for="id_preview_rules">Preview rules:</label></th>
                    <td>{{ form.preview_rules.errors }}{{ form.preview_rules }}</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <h3>Dates</h3>
                    </td>
                </tr>
                <tr>
                    <th><label for="id_start_date">Start date:</label></th>
                    <td>{{ form.start_date.errors }}{{ form.start_date }}{% include 'tips/timeZone.html' %}</td>
                </tr><tr>
                    <th><label for="id_submission_deadline_date">Submission deadline date:</label></th>
                    <td>{{ form.submission_deadline_date.errors }}{{ form.submission_deadline_date }}</td>
                </tr>
                <tr>
                    <th><label for="id_vote_time_quantity">Voting is open for:</label></th>
                    <td>{{ form.vote_time_quantity.errors }}{{ form.vote_time_measurement.errors}}{{ form.vote_time_quantity }}{{ form.vote_time_measurement }}</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <h3>Listening Party</h3>
                    </td>
                </tr>
                <tr>
                    <th><label for="id_have_listening_party">Have listening party:</label></th>
                    <td>{{ form.have_listening_party.errors }}{{ form.have_listening_party }}{% include 'tips/listeningParty.html' %}</td>
                </tr>
                <tr id="div_immediately">
                    <th><label for="id_party_immediately">Immediately:</label></th>
                    <td>{{ form.party_immediately.errors }}{{ form.party_immediately}}</td>
                </tr>
                <tr id="div_lp_date">
                    <th><label for="id_listening_party_date">Listening party date:</label></th>
                    <td>{{ form.listening_party_date.errors }}{{ form.listening_party_date }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="{% block submit_text %}Create Competition{% endblock %}" /></td>
                </tr>
            </table>
            </fieldset>
        </form>
    </div>
{% endblock %}

templates/arena/entry-voting.jst.html
<div class="entry-vote-box">
    <% if (entry.voted_for) { %>
        <span class="voted"><a href="#" id="unvote-<%= i %>" title="Undo this vote"></a></span>
    <% } else { %>
        <% if (json.votes.left > 0 && entry.owner.id != json.user.id) { %>
            <span class="unvoted"><a href="#" id="vote-<%= i %>" title="Vote for this entry"></a></span>
        <% } %>
    <% } %>
</div>