urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from django.views.generic.simple import direct_to_template, redirect_to

admin.autodiscover()

urlpatterns = patterns('',
    (r'^arena/', include('competitions.urls')),
    (r'^chat/', include('chat.urls')),
    (r'^workbench/', include('workshop.urls')),
    (r'^admin/', include(admin.site.urls)),

    url(r'^$', 'main.views.home', name='home'),

    url(r'^ajax/login_state/$', 'main.views.ajax_login_state', name="ajax_login_state"),
    # if you change this, change LOGIN_URL in settings too.
    url(r'^ajax/login/$', 'main.views.ajax_login', name="ajax_login"),
    url(r'^ajax/logout/$', 'main.views.ajax_logout', name="ajax_logout"),
    url(r'^ajax/comment/$', 'main.views.ajax_comment', name="ajax_comment"),
    url(r'^ajax/delete_comment/$', 'main.views.ajax_delete_comment', name="ajax_delete_comment"),
    url(r'^ajax/edit_comment/$', 'main.views.ajax_edit_comment', name="ajax_edit_comment"),

    url(r'^article/([\w\d-]+)/$', 'main.views.article', name='article'),

    url(r'^plans/$', 'main.views.plans', name='plans'),

    url(r'^user/(.+)/$', 'main.views.userpage', name='userpage'),
    url(r'^band/(.+)/$', 'main.views.bandpage', name='bandpage'),

    url(r'^login/$', 'main.views.user_login', name="user_login"),
    url(r'^logout/$', 'main.views.user_logout', name="user_logout"),
    url(r'^signup/$', 'main.views.user_register', name="register"),
    url(r'^signup/pending/$', 'main.views.register_pending', name="register_pending"),
    url(r'^signup/(.+)/$', 'main.views.user_register_plan', name="register_plan"),
    url(r'^confirm/(.+)/(.+)/$', 'main.views.confirm', name="confirm"),

    url(r'^contact/$', 'main.views.contact', name="contact"),
    
    url(r'^legal/$', direct_to_template, {'template': 'legal/home.html'}, name="legal"),
    url(r'^legal/privacy/$', direct_to_template, {'template': 'legal/policy.html'}, name="policy"),
    url(r'^legal/terms/$', direct_to_template, {'template': 'legal/terms.html'}, name="terms"),

    url(r'^account/$', 'main.views.account_plan', name="account"),
    url(r'^account/plan/$', 'main.views.account_plan', name="account.plan"),
    url(r'^account/email/$', 'main.views.account_email', name="account.email"),
    url(r'^account/preferences/$', 'main.views.account_preferences', name="account.preferences"),
    url(r'^account/password/$', 'main.views.account_password', name="account.password"),
    url(r'^account/password/reset/$', 'main.views.account_password_reset', name="account.password.reset"),

    url(r'^landing/$', 'main.views.landing', name='landing'),
    url(r'^dashboard/$', 'main.views.dashboard', name='dashboard'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^500/$', direct_to_template, {'template': '500.html'}, name='404'),
        url(r'^404/$', direct_to_template, {'template': '404.html'}, name='500'),
    )

base/models.py
from django.db import models
from django.contrib.auth.models import User

import string

def create_url(title, is_unique=None):
    """
    creates a clean and safe url to use based on a name.
    calls is_unique with a candidate to see if it is unique.
    """
    allowed_chars = string.letters + string.digits + r'_-.'
    replacement = '_'

    # break title into url safe string
    safe_title = ''
    for c in title.lower():
        if c in allowed_chars:
            safe_title += c
        else:
            safe_title += replacement

    if is_unique is None:
        return safe_title

    # append digits until it is unique
    suffix = 2
    proposed = safe_title
    while not is_unique(proposed):
        proposed = safe_title + str(suffix)
        suffix += 1

    return proposed

class SerializableModel(models.Model):
    PUBLIC, OWNER, ADMIN = range(3)

    # admin attrs are assumed by default
    PUBLIC_ATTRS = ()
    OWNER_ATTRS = ()

    def process_chains(self, chains):
        forwards = []
        new_chains = []

        for chain in chains:
            pieces = chain.split('.')
            forwards.append(pieces[0])
            if len(pieces) > 1:
                new_chains.append('.'.join(pieces[1:]))

        return (forwards, new_chains)
        
    def process_access(self, access):
        if access == self.OWNER:
            # de-esclate from owner to public when forwarding
            return self.PUBLIC
        else:
            return access

    def to_dict(self, access=PUBLIC, chains=[]):
        forwards, new_chains = self.process_chains(chains)
        new_access = self.process_access(access)

        def has_access(field):
            return access >= self.ADMIN or (field.name in self.PUBLIC_ATTRS and access >= self.PUBLIC) or (field.name in self.OWNER_ATTRS and access >= self.OWNER)

        from django.db.models.fields.related import ManyToManyField, ForeignKey
        opts = self._meta
        accessible_fields = filter(has_access, opts.fields+opts.many_to_many)

        data = {'id': self.pk}
        for field in accessible_fields:
            follow = field.name in forwards
            if isinstance(field, ManyToManyField):
                if self.pk is None:
                    data[field.name] = []
                elif follow:
                    data[field.name] = [obj.to_dict(new_access, new_chains) for obj in field.value_from_object(self)]
                else:
                    data[field.name] = [obj.pk for obj in field.value_from_object(self)]
            elif isinstance(field, ForeignKey):
                id = field.value_from_object(self)
                if id is not None and follow:
                    model = field.related.parent_model
                    instance = model.objects.get(pk=id)
                    if issubclass(model, User):
                        data[field.name] = instance.get_profile().to_dict(new_access, new_chains)
                    else:
                        data[field.name] = instance.to_dict(new_access, new_chains)
                else:
                    data[field.name] = id
            else:
                data[field.name] = field.value_from_object(self)

        return data

    class Meta:
        abstract = True

main/models.py
from base.models import SerializableModel, create_url
from competitions.models import ThumbsUp
from datetime import datetime, timedelta
from django.contrib.auth.models import User
from django.db import models
from main import design
import workshop
import competitions
import hashlib

class BandMember(SerializableModel):
    MANAGER, BAND_MEMBER, CRITIC, FAN, BANNED = range(5)
    ROLE_CHOICES = (
        (MANAGER, u'Manager'), # full privileges
        (BAND_MEMBER, u'Band member'), # full privileges except band admin
        (CRITIC, u'Critic'), # can view and post comments in project manager
        (FAN, u'Fan'), # regular site user
        (BANNED, u'Banned'), # this person is blacklisted
    )

    PUBLIC_ATTRS = (
        'user',
        'band',
        'role',
    )

    OWNER_ATTRS = (
        'space_donated',
    )

    user = models.ForeignKey(User)
    band = models.ForeignKey('main.Band')
    role = models.IntegerField(choices=ROLE_CHOICES, default=MANAGER)
    space_donated = models.BigIntegerField(default=0)

    def percent_contrib(self):
        "return the % of the number of projectversions are this member's"
        total_set = workshop.models.ProjectVersion.objects.filter(project__band=self.band)
        total_count = total_set.count()
        if total_count == 0:
            return 0
        mine_count = total_set.filter(owner=self.user).count()
        return float(mine_count) / float(total_count) * 100

    def __unicode__(self):
        return u'{0} - {1}: {2}'.format(self.band.title, dict(BandMember.ROLE_CHOICES)[self.role], self.user.username)


class Band(SerializableModel):
    FULL_OPEN, OPEN_SOURCE, TRANSPARENT, NO_CRITIQUE, PRIVATE = range(5)
    OPENNESS_CHOICES = (
        # completely open. anyone with an account and not banned can contribute.
        (FULL_OPEN, 'Fully open'),
        # open source but only band members can contribute
        (OPEN_SOURCE, 'Open source'),
        # anyone can critique (view and post comments in project manager)
        # but source is protected
        (TRANSPARENT, 'Transparent'),
        # anyone can view and listen to projects but feedback is locked
        (NO_CRITIQUE, 'Critiquing disabled'),
        # private band, the public can only see what the band releases
        (PRIVATE, 'Private'),
    )

    PUBLIC_ATTRS = (
        'title',
        'url',
        'openness',
        'bio',
    )
    OWNER_ATTRS = (
        'concurrent_editing',
        'total_space',
        'used_space',
    )
    date_created = models.DateTimeField()

    # if you want to change the title, you need to do band.rename(new_title)
    title = models.CharField(max_length=100)
    # automatically created. as close to title as possible yet unique and
    # file system safe.
    url = models.CharField(max_length=110, unique=True, null=True)

    # openness is what applies to people who aren't explicitly in the 
    # band members list.
    openness = models.IntegerField(choices=OPENNESS_CHOICES, default=PRIVATE)

    # band information
    bio = models.TextField(blank=True, null=True)

    # True if people have to check stuff out to work on it
    concurrent_editing = models.BooleanField(default=False)

    # how much space does the band have in their account in bytes
    # users can dole out their total_space to a band.
    # the default should be the total_space from the free plan in the database.
    total_space = models.BigIntegerField()
    used_space = models.BigIntegerField(default=0)
    # how long has it been since used_space > total_space
    abandon_date = models.DateTimeField(blank=True, null=True)

    def is_read_only(self):
        return self.used_space > self.total_space

    def save(self, *args, **kwargs):
        if not self.id:
            self.date_created = datetime.now()

        if self.used_space > self.total_space and self.abandon_date is None:
            self.abandon_date = datetime.now()
        elif self.used_space <= self.total_space and self.abandon_date is not None:
            self.abandon_date = None

        if self.url is None:
            self.create_url()

        self._save(*args, **kwargs)

    def _save(self, *args, **kwargs):
        super(Band, self).save(*args, **kwargs)

    def create_url(self):
        self.url = create_url(self.title.lower(), lambda proposed: Band.objects.filter(url=proposed).count() == 0)

    def rename(self, new_name):
        # if it's the same, do nothing
        if self.title == new_name:
            return

        self.title = new_name
        self.create_url()

    def permission_to_view_source(self, user):
        "Returns whether a user can view samples and project file for the band."
        if self.openness == Band.FULL_OPEN:
            return True

        return self.permission_to_work(user)

    def permission_to_work(self, user):
        "Returns whether a user can check out and check in projects."
        if not user.is_authenticated():
            return False

        if self.openness == Band.FULL_OPEN:
            return True

        # get the BandMember for this user
        try:
            member = BandMember.objects.get(user=user, band=self)
        except BandMember.DoesNotExist:
            return False

        return member.role in (BandMember.MANAGER, BandMember.BAND_MEMBER)

    def permission_to_critique(self, user):
        if not user.is_authenticated():
            return False

        if self.openness in (Band.FULL_OPEN, Band.OPEN_SOURCE, Band.TRANSPARENT):
            return True

        # get the BandMember for this user
        try:
            member = BandMember.objects.get(user=user, band=self)
        except BandMember.DoesNotExist:
            return False

        return member.role in (BandMember.MANAGER, BandMember.BAND_MEMBER, BandMember.CRITIC)

    def permission_to_invite(self, user):
        if not user.is_authenticated():
            return False

        if self.openness == Band.FULL_OPEN:
            return True

        # get the BandMember for this user
        try:
            member = BandMember.objects.get(user=user, band=self)
        except BandMember.DoesNotExist:
            return False

        return member.role == BandMember.MANAGER

    def __unicode__(self):
        return self.title


class AccountPlan(SerializableModel):
    """
    The payment plan and features that a user has
    """

    PUBLIC_ATTRS = (
        'title',
        'usd_per_month',
        'total_space',
        'band_count_limit',
    )

    title = models.CharField(max_length=50)
    url = models.CharField(max_length=20, unique=True)
    # how much the user has to pay per month
    usd_per_month = models.FloatField()
    # byte count limit of their account
    total_space = models.BigIntegerField()
    # how many bands can they make
    band_count_limit = models.IntegerField()

    def __unicode__(self):
        return "%s - $%s/mo" % (self.title, self.usd_per_month)

class Transaction(models.Model):
    """
    Represents a request to get a recurring billing token from Amazon.
    we use the Transaction id for caller_reference.
    """
    transaction_id = models.CharField(max_length=256, null=True, blank=True)
    request_id = models.CharField(max_length=256, null=True, blank=True) 
    token_id = models.CharField(max_length=65, null=True, blank=True)
    expiry = models.CharField(max_length=20, null=True, blank=True)
    timestamp = models.DateTimeField()

    user = models.ForeignKey(User)
    amount = models.FloatField()
    # true when the amount is successfully paid
    confirmed = models.BooleanField(default=False)
    # the plan that will be given to the user upon successful payment
    plan = models.ForeignKey('AccountPlan')

    def save(self, *args, **kwargs):
        if not self.id:
            self.timestamp = datetime.now()
        self._save(*args, **kwargs)

    def _save(self, *args, **kwargs):
        super(Transaction, self).save(*args, **kwargs)

class Profile(SerializableModel):
    PUBLIC_ATTRS = (
        'user',
        'solo_band',
        'date_activity',
        'bio',
    )
    OWNER_ATTRS = (
        'activated',
        'competitions_bookmarked',
        'plan',
        'purchased_bytes',
        'usd_per_month',
        'band_count_limit',
        'plugins',
        'studios',
        'assume_uploaded_plugins_owned',
    )
    GRAVATAR_DOMAIN = (
        # SSL=False
        "http://www.gravatar.com",
        # SSL=True
        "https://secure.gravatar.com",
    )
        

    user = models.ForeignKey(User, unique=True)
    solo_band = models.ForeignKey(Band)
    activated = models.BooleanField()
    activate_code = models.CharField(max_length=256)
    date_activity = models.DateTimeField()

    bio = models.TextField(blank=True, null=True)

    # the competitions the player has bookmarked
    competitions_bookmarked = models.ManyToManyField('competitions.Competition', blank=True, related_name='competitions_bookmarked')

    # account stuff. When a user signs up for a plan, this is inherited from
    # the plan's data, but it can be overridden here.
    plan = models.ForeignKey(AccountPlan, blank=True, null=True)
    # how many bands can the user create
    band_count_limit = models.IntegerField(default=1)
    # how much space does the user have in their account in bytes
    # the actual accounting is done in Band. this field is simply where purchased bytes
    # are accumulated, which are then doled out to one or more Bands' total_space
    purchased_bytes = models.BigIntegerField(default=0)

    # billing information
    # if they are on a monthly plan, this field will be greater than 0.
    usd_per_month = models.FloatField(default=0.0)
    # when the billing cron job runs, it checks for account_expire_date which
    # is in the past and bills, adding a month. This means when a person signs up,
    # we set the date to now() and allow the cron job to bill them.

workshop/forms.py
from django import forms
from workshop import design

class NewProjectForm(forms.Form):
    title = forms.CharField(max_length=100, error_messages={'required': design.this_field_is_required})
    file_source = forms.FileField(label="Project file", error_messages={ 'required': design.this_field_is_required})
    file_mp3 = forms.FileField(label="MP3 Preview", required=False)
    comments = forms.CharField(max_length=3000, required=False, widget=forms.Textarea)

    def clean_file_mp3(self):
        filename = self.cleaned_data['file_mp3']

        if filename is None:
            return filename

        if filename.name[-3:].lower() != 'mp3':
            raise forms.ValidationError(design.uploaded_file_must_be_mp3)

        return filename

class NewBandForm(forms.Form):
    band_name = forms.CharField(max_length=100, error_messages={'required': design.this_field_is_required})

class RenameBandForm(forms.Form):
    new_name = forms.CharField(max_length=100, error_messages={'required': design.this_field_is_required})

class RenameProjectForm(forms.Form):
    title = forms.CharField(max_length=100, error_messages={'required': design.you_must_have_a_title})
    comments = forms.CharField(max_length=3000, required=False, widget=forms.Textarea)
    project = forms.IntegerField()

base/views.py
# Create your views here.

templates/workbench/action_upload_samples.jst.html
<li><a id="upload-samples" href="#">Upload samples</a>{% include 'tips/uploadSamples.html' %}</li>

templates/workbench/band.html
{% extends 'workbench/base.html' %}

{% block css %}band.pre.css{% endblock %}

{% block extra_header %}
    {{ block.super }}
    <script type="text/javascript">
        var band_id = {{ band.id }};
    </script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/login.pre.js"></script>
    {% if permission %}
        {% include 'player/script_player.html' %}
        <script type="text/javascript" src="{{ MEDIA_URL }}js/workbench/band.pre.js"></script>
    {% endif %}
{% endblock %}

{% block content %}
    {% if permission %}
        {% include 'workbench/tools.html' %}
        <div id="bread">
            <a href="{% url home %}">Home</a>
            &gt;
            <a href="{% url workbench.home %}">Workbench</a>
            &gt;
            <span class="dest">{{ band.title }}</span>
        </div>
        <div id="band-spacemeter">
            {% include 'loading.html' %}
        </div>
        <div id="filters">
            {% include 'loading.html' %}
        </div>
        <div id="new_project">
            <a href="{% url workbench.create_project band.id %}">New Project</a>
        </div>
        <div>
            <input type="text" id="search" class="inactive" />
        </div>
        <div id="project-list">
            {% include 'loading.html' %}
        </div>
    {% else %}
        <p>
            Only {{ band.title }} band members can access this page.
        </p>
    {% endif %}
{% endblock %}

templates/workbench/band_invite.html
{% extends 'workbench/base.html' %}

{% block extra_header %}
    {{ block.super }}
    <script type="text/javascript">
        var band_id = {{ band.id }};
    </script>
    {% if permission %}
        <script type="text/javascript" src="{{ MEDIA_URL }}js/workbench/band_invite.pre.js"></script>
    {% endif %}
{% endblock %}

{% block title %}Add a Band Member - {{ block.super }}{% endblock %}

{% block login %}
    {% include 'login_area.html' %}
{% endblock %}

{% block content %}
    {% if permission %}
        {% include 'workbench/tools.html' %}
        <div id="bread">
            <a href="{% url home %}">Home</a>
            &gt;
            <a href="{% url workbench.home %}">Workbench</a>
            &gt;
            <a href="{% url workbench.band band.id %}">{{ band.title }}</a>
            &gt;
            <span class="dest">Add a Band Member</span>
        </div>
        <div class="textblock">
            <div id="invite-link">
                <h1><a href="#">Create Invitation Link</a></h1>
                <div class="dropdown" style="display: none;">
                    <div id="copy-area">
                    {% include 'loading.html' %}
                    </div>
                </div>
            </div>
            <div id="invite-email">
                <h1><a href="#">Invite by Email</a></h1>
                <div class="dropdown" style="display: none;">
                    Band mate's email: <input type="text" id="email-box" value="" /><input type="button" value="Invite" id="email-button" />
                    <div class="success" style="display: none;">
                        {% include 'success.html' %}
                    </div>
                </div>
            </div>
            <div id="invite-local">
                <h1><a href="#">Invite a SolidComposer User</a></h1>
                <div class="dropdown" style="display: none;">
                    User name: <input type="text" id="local-box" value="" /><input type="button" value="Invite" id="local-button" />
                    {% include 'tips/inviteLocalUser.html' %}
                    <div class="success" style="display: none;">
                        {% include 'success.html' %}
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <p>
            Only band managers can invite people to join.
        </p>
    {% endif %}
{% endblock %}

templates/workbench/band_settings.html
{% extends 'workbench/base.html' %}

{% block title %}Settings - {{ band.title }} - {{ block.super }}{% endblock %}

{% block login %}
    {% include 'login_area.html' %}
{% endblock %}

{% block content %}
    {% include 'workbench/tools.html' %}
    <div id="bread">
        <a href="{% url home %}">Home</a>
        &gt;
        <a href="{% url workbench.home %}">Workbench</a>
        &gt;
        <a href="{% url workbench.band band.id %}">{{ band.title }}</a>
        &gt;
        <span class="dest">Settings</span>
    </div>
    <div class="textblock">
        <h1>Band Settings</h1>
        {% if permission %}
            <h2>Rename Band</h2>
            {% if err_msg %}
                <div class="err">
                    <p>{{ err_msg }}</p>
                </div>
            {% endif %}
            <form action="." method="post">
                <table>
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Rename" /></td>
                    </tr>
                </table>
            </form>
            <h2>Members</h2>
            <ul>
            {% for member in band.bandmember_set.all %}
                {% with member.user as user %}
                    <div>
                        {% include 'username.html' %}
                    </div>
                {% endwith %}
            {% endfor %}
            </ul>
        {% else %}
            <p>
                {{ err_msg }}
            </p>
        {% endif %}
    </div>
    
{% endblock %}

templates/workbench/base.html
{% extends 'base.html' %}

{% block title %}Workbench - {{ block.super }}{% endblock %}

{% block css %}workbench.pre.css{% endblock %}

{% block login %}
    {% include 'login_div.html' %}
{% endblock %}

{% block extra_header %}
    {% include 'sc_script_framework.html' %}
    {{ block.super }}
{% endblock %}

{% block nav_workbench_li_class %}selected{% endblock %}

{% block nav2 %}
    {% block tools_wrapper %}
        <ul id="tools">
            {% block tools %}
                <li class="plus"><a href="{% url workbench.create_band %}">Create a New Band</a></li>
            {% endblock %}
        </ul>
    {% endblock %}
    {% block middle_nav2 %}{% endblock %}
    <div id="bread">
        <a href="{% url home %}">Home</a>
        &gt;
        {% block bread_workbench %}
            <a href="{% url workbench.home %}">Workbench</a>
        {% endblock %}
        {% block bread_crumb %}
        {% endblock %}
    </div>
    {% block extra_nav2 %}{% endblock %}
{% endblock %}

templates/workbench/entryTypeEnum.jst.html
{
    SONG_CRITIQUE:      0,
    SONG_CHECKED_IN:    1,
    SONG_CHECKED_OUT:   2,
    SAMPLES_UPLOADED:   3,
    SONG_RENAMED:       4,
    POKE:               5,
    BAND_MEMBER_JOIN:   6,
    BAND_MEMBER_QUIT:   7,
    NEW_PROJECT:        8,
    SONG_JUST_CHECK_IN: 9,
    SPACE_ALLOCATED_CHANGE: 10
}

templates/workbench/filters.jst.html
<ul id="tabnav">
    <% for (var filterId in filters) { %>
        <li id="filter-<%=filterId%>" class="unselected">
            <a class="filter" data-filterid="<%=filterId%>" href="#<%=filterId%>">
                <%=filters[filterId].caption%> (<%=filters[filterId].count%>)
            </a>
        </li>
    <% } %>
</ul>

templates/workbench/invitation_link_email.html
{% extends 'email.html' %}

{% block content %}
    <h1>{{ user.username }} wants you to join their band, {{ band.title }}</h1>
    <p>
        If you'd like to join forces with {{ user.username }}, enter this link into your browser:
        <br />
        {{ invite.redeemHyperlink }}
        <br />
    </p>
    <p>
        If this doesn't interest you, simply ignore this message.
    </p>
{% endblock %}

templates/workbench/new_project.html
{% extends 'workbench/base.html' %}

{% block title %}New Project - {{ block.super }}{% endblock %}

{% block login %}
    {% include 'login_area.html' %}
{% endblock %}

{% block content %}
    {% if permission %}
        {% include 'workbench/tools.html' %}
        <div id="bread">
            <a href="{% url home %}">Home</a>
            &gt;
            <a href="{% url workbench.home %}">Workbench</a>
            &gt;
            <a href="{% url workbench.band band.id %}">{{ band.title }}</a>
            &gt;
            <span class="dest">New Project</span>
        </div>
        <div class="textblock">
            <h1>New Project</h1>
            {% if err_msg %}
            <div class="err">
                <p>{{ err_msg }}</p>
            </div>
            {% endif %}
            <form action="." method="post" enctype="multipart/form-data">
                <table>
                    <tr>
                        <th>
                            <label for="id_title">{{ form.title.label }}:</label>
                        </th>
                        <td>
                            {{ form.title.errors }}{{ form.title }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <label for="id_file_source">{{ form.file_source.label }}:</label>
                        </th>
                        <td>
                            {{ form.file_source.errors }}{{ form.file_source }}
                        </td>
                        <td>
                            {% include 'tips/uploadProjectFileInput.html' %}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <label for="id_file_mp3">{{ form.file_mp3.label }}:</label>
                        </th>
                        <td>
                            {{ form.file_mp3.errors }}{{ form.file_mp3 }}
                        </td>
                        <td>
                            {% include 'tips/uploadPreviewMp3.html' %}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <label for="id_comments">{{ form.comments.label }}:</label>
                        </th>
                        <td>
                            {{ form.comments.errors }}{{ form.comments }}
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Create" /></td>
                    </tr>
                </table>
            </form>
        </div>
    {% else %}
        <p>
            Only {{ band.title }} band members can create new projects.
        </p>
    {% endif %}
{% endblock %}

templates/workbench/project.html
{% extends 'workbench/base.html' %}

{% block title %}{{ project.title }} - {{ block.super }}{% endblock %}

{% block css %}project.pre.css{% endblock %}

{% block extra_header %}
    {{ block.super }}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/webtoolkit.aim.js"></script>
    <script type="text/javascript">
        var band_id = {{ band.id }};
        var project_id = {{ project.id }};
    </script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/login.pre.js"></script>
    {% include 'player/script_player.html' %}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/workbench/project.pre.js"></script>
{% endblock %}


{% block content %}
    <div id="bread">
        <a href="{% url home %}">Home</a>
        &gt;
        <a href="{% url workbench.home %}">Workbench</a>
        &gt;
        <a href="{% url workbench.band band.id %}">{{ band.title }}</a>
        &gt;
        <span class="dest">{{ project.title }}</span>
    </div>
    <div id="projects">
        {% include 'loading.html' %}
    </div>
    <div id="footer-data">
        {% include 'loading.html' %}
    </div>
{% endblock %}

templates/workbench/project_footer.jst.html
<% if (project.forked_from) { %>
    <p>Forked from <a href="<%=urls.project_version(project.forked_from.project.id, project.forked_from.version)%>"><%=project.forked_from.song.title%></a></p>
<% } else if (project.merged_from) { %>
    <div id="merge">
        <ul>
            <% for (var i=0; i<project.merged_from.length; ++i) { var merge = project.merged_from[i]; %>
                <li>
                    <a href="<%=urls.project_version(merge.project.id, merge.version)%>"><%=project.merged_from[i].song.title%></a>
                </li>
            <% } %>
        </ul>
    </div>
<% } %>

templates/workbench/sample_upload_row.jst.html
<tr>
    <td>
        Sample file(s):
    </td>
    <td>
        <input type="file" name="file" multiple="multiple" />
        {% include 'tips/uploadSampleBox.html' %}
    </td>
</tr>

templates/workbench/spacemeter.jst.html
<% (function (numerator, denominator, number_formatter_func) {
    var percent = (denominator > 0) ? (numerator / denominator * 100) : 100;
    if (percent > 100) { percent = 100; }
%>
    <div class="meter">
        <div class="bar">
            <div class="bg"> 
                <div class="used" style="width: <%= percent %>%; background-color: <%
                if (percent < 50) {
                    %>#00bb35<%
                } else if (percent < 75) {
                    %>#e79c29<%
                } else {
                    %>#ff2b3b<%
                }
                %>;">
                    <div class="border">
                        <span><%= number_formatter_func(numerator) %> / <%= number_formatter_func(denominator) %></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% })(numerator, denominator, number_formatter_func); %>